#
name: Automatic doc checks

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '/**'   # Removed docs as everything is in the root directory

  workflow_dispatch:
    # Manual trigger


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@55b0d3238587f2cf3a4f1d7199c8b15dc71d573b
    with:
      working-directory: "/"
      fetch-depth: 0
