#
name: Automatic doc checks

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '/**'   # Removed docs as everything is in the root directory

  workflow_dispatch:
    # Manual trigger


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@a6b7423be729d4e5ec33801cc0858046a6c90466
    with:
      working-directory: "/"
      fetch-depth: 0
