#
name: Automatic doc checks

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '/**'   # Removed docs as everything is in the root directory

  workflow_dispatch:
    # Manual trigger


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  documentation-checks:
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@e4fb94df31df30812af655d9b99c7900d34da47b
    with:
      working-directory: "/"
      fetch-depth: 0
