name: CLA check
on: [pull_request_target]

jobs:
  check-for-cla:
    name: Check if author has signed the Canonical CLA
    runs-on: ubuntu-latest
    steps:
    - name: Check if CLA signed
      uses: canonical/has-signed-canonical-cla@1399a98cde76a66912c1a75b23f6f306ea814f1c # v2
