name: Update API specs
on:
  workflow_dispatch:
  # Run daily after midnight UTC
  schedule:
  - cron: '0 1 * * *'

jobs:
  update-api-specs:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - name: Set up Anbox Cloud
      uses: canonical/anbox-cloud-github-action@ef0690184b1c8fd11e3385669726297bc2e3d368
      with:
        channel: latest/stable
    - name: Determine appliance version
      id: snap_version
      run: |
        echo "value=$(snap info anbox-cloud-appliance | awk '/installed/{print $2}')" >> "$GITHUB_OUTPUT"
    - name: Extract API spec from AMS
      run: |
        sudo apt update
        sudo apt install -y jq yq
        # Don't allow us to succeed if the actual curl command fails
        set -o pipefail
        curl \
          --unix-socket /var/snap/anbox-cloud-appliance/common/ams-unix.socket \
          s/1.0/swagger.json | yq -y > ./reference/api-reference/ams-api.yaml
        sudo curl \
          --unix-socket /var/snap/anbox-cloud-appliance/common/gateway/internal.sock \
          s/1.0/swagger.json | yq -y > ./reference/api-reference/gateway-api.yaml
    - name: Create PR
      uses: canonical/create-pull-request@26af5f052357f28ddd9cd69b924547c9a18fa853
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "feat: update API specs from ${{ steps.snap_version.outputs.value }}"
        branch-name: new-branch
        title: Update API specs from ${{ steps.snap_version.outputs.value }}
        body: |
          This updates the AMS API specification as taken from the `anbox-cloud-appliance` as of
          version ${{ steps.snap_version.outputs.value }}.

          You have to close and reopen the PR to trigger checks.
        repository: canonical/anbox-cloud-docs
        upsert: true
        ignore-no-changes: true
